# Verwende ein offizielles Node-Image als Basis
FROM node:20.12.2 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html


COPY nginx.conf /etc/nginx/nginx.conf

# Port freigeben
EXPOSE 80

# Nginx-Server starten
CMD ["nginx", "-g", "daemon off;"]
